// GENERATED from the backend's access catalog (schoolOS_backend/apps/access/catalog).
// Do not edit by hand: regenerate it when the backend catalog changes.
// A test checks that every screen in the app's menus is in this list.

class CatalogEntry {
  const CatalogEntry(this.key, this.label, this.area, this.roles, {this.essential = false, this.grantable = true, this.sensitive = false});
  final String key;
  final String label;
  final String area;
  final Set<String> roles;
  final bool essential;
  final bool grantable;
  final bool sensitive;
}

const accessCatalogEntries = <CatalogEntry>[
  CatalogEntry('owner.overview', 'Executive Overview', 'Owner', {'proprietor'}, essential: true),
  CatalogEntry('owner.finance', 'Owner Finance', 'Owner', {'proprietor'}, sensitive: true),
  CatalogEntry('owner.finance-approvals', 'Concession Approvals', 'Owner', {'proprietor'}, sensitive: true),
  CatalogEntry('owner.enrollment', 'Enrollment & Admissions', 'Owner', {'proprietor'}),
  CatalogEntry('owner.staff', 'Staff & HR', 'Owner', {'proprietor'}),
  CatalogEntry('owner.jobs', 'Jobs & Delegation', 'Owner', {'proprietor'}, sensitive: true),
  CatalogEntry('owner.staff-profiles', 'Staff Profiles', 'Owner', {'proprietor'}, sensitive: true),
  CatalogEntry('owner.payroll', 'Payroll & Salaries', 'Owner', {'proprietor'}, sensitive: true),
  CatalogEntry('owner.reports', 'Executive Reports', 'Owner', {'proprietor'}, sensitive: true),
  CatalogEntry('owner.campuses', 'Campus Comparison', 'Owner', {'proprietor'}),
  CatalogEntry('owner.ai', 'Proprietor AI', 'Owner', {'proprietor'}),
  CatalogEntry('owner.structure', 'Structure & Leadership', 'Owner', {'proprietor'}),
  CatalogEntry('owner.appearance', 'School Appearance', 'Owner', {'proprietor'}),
  CatalogEntry('owner.school-life', 'School Life', 'Owner', {'proprietor'}),
  CatalogEntry('owner.access', 'Access & Activities', 'Owner', {'proprietor'}, grantable: false, sensitive: true),
  CatalogEntry('principal.dashboard', 'Dashboard', 'Principal', {'principal'}, essential: true),
  CatalogEntry('principal.teachers', 'Teachers', 'Principal', {'principal'}, sensitive: true),
  CatalogEntry('principal.staff-profiles', 'Staff Profiles', 'Principal', {'principal'}, sensitive: true),
  CatalogEntry('principal.assignments', 'Teaching Assignments', 'Principal', {'principal'}),
  CatalogEntry('principal.academics', 'Academics', 'Principal', {'principal'}),
  CatalogEntry('principal.students', 'Students', 'Principal', {'principal'}),
  CatalogEntry('principal.attendance', 'Attendance', 'Principal', {'principal'}),
  CatalogEntry('principal.approvals', 'Approvals', 'Principal', {'principal'}),
  CatalogEntry('principal.results', 'Results & Reports', 'Principal', {'principal'}),
  CatalogEntry('principal.timetable', 'Timetable', 'Principal', {'principal'}),
  CatalogEntry('principal.excursions', 'Excursions', 'Principal', {'principal'}),
  CatalogEntry('principal.gallery', 'Media Gallery', 'Principal', {'principal'}),
  CatalogEntry('principal.alumni', 'Alumni Management', 'Principal', {'principal'}, sensitive: true),
  CatalogEntry('principal.communication', 'Communication', 'Principal', {'principal'}),
  CatalogEntry('principal.incidents', 'Incidents', 'Principal', {'principal'}),
  CatalogEntry('principal.ai', 'Principal AI', 'Principal', {'principal'}),
  CatalogEntry('principal.performance', 'School Performance', 'Principal', {'principal'}),
  CatalogEntry('principal.profile', 'Profile', 'Principal', {'principal'}),
  CatalogEntry('principal.community', 'Community', 'Principal', {'principal'}),
  CatalogEntry('administrator.dashboard', 'Dashboard', 'Administrator', {'administrator'}, essential: true),
  CatalogEntry('administrator.admissions', 'Admissions Pipeline', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.website', 'Website Manager', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.registration', 'Student Registration', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.students', 'Students & Families', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.academics', 'Academic Structure', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.curriculum', 'Subjects & Curriculum', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.timetable', 'Timetable', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.alumni', 'Alumni Management', 'Administrator', {'administrator'}, sensitive: true),
  CatalogEntry('administrator.staff', 'Staff Records', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.staff-profiles', 'Staff Profiles', 'Administrator', {'administrator'}, sensitive: true),
  CatalogEntry('administrator.staff-attendance', 'Staff Attendance', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.records', 'Records & Documents', 'Administrator', {'administrator'}, sensitive: true),
  CatalogEntry('administrator.lifecycle', 'Transfers & Promotion', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.attendance', 'Attendance Desk', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.operations', 'Operations', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.notices', 'Notices', 'Administrator', {'administrator'}),
  CatalogEntry('administrator.community', 'Community', 'Administrator', {'administrator'}),
  CatalogEntry('finance.dashboard', 'Dashboard', 'Finance office', {'accountant'}, essential: true),
  CatalogEntry('finance.fee-structure', 'Fee Structure', 'Finance office', {'accountant'}),
  CatalogEntry('finance.scholarships', 'Scholarships & Discounts', 'Finance office', {'accountant'}),
  CatalogEntry('finance.collections', 'Smart Collections', 'Finance office', {'accountant'}),
  CatalogEntry('finance.reminders', 'Fee Reminders', 'Finance office', {'accountant'}),
  CatalogEntry('finance.store', 'School Store', 'Finance office', {'accountant'}),
  CatalogEntry('finance.mandates', 'Payment Mandates', 'Finance office', {'accountant'}),
  CatalogEntry('finance.debt-aging', 'Outstanding & Aging', 'Finance office', {'accountant'}),
  CatalogEntry('finance.receipts', 'Receipts', 'Finance office', {'accountant'}),
  CatalogEntry('finance.accounts', 'Student Accounts', 'Finance office', {'accountant'}, sensitive: true),
  CatalogEntry('finance.reconciliation', 'Reconciliation', 'Finance office', {'accountant'}, sensitive: true),
  CatalogEntry('finance.expenses', 'Expenses & Income', 'Finance office', {'accountant'}, sensitive: true),
  CatalogEntry('finance.payroll', 'Payroll Handoff', 'Finance office', {'accountant'}, sensitive: true),
  CatalogEntry('finance.reports', 'Reports', 'Finance office', {'accountant'}),
  CatalogEntry('finance.ai', 'Finance AI', 'Finance office', {'accountant'}),
  CatalogEntry('finance.community', 'Community', 'Finance office', {'accountant'}),
  CatalogEntry('teacher.dashboard', 'Dashboard', 'Teacher', {'teacher'}, essential: true),
  CatalogEntry('teacher.timetable', 'My Timetable', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.classes', 'My Classes', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.attendance', 'Attendance', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.lesson-plans', 'Lesson Plans', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.weekly-progress', 'Weekly Learning', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.syllabus', 'Syllabus', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.assignments', 'Assignments', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.assessments', 'Assessments', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.cbt', 'CBT Practice', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.learning-progress', 'Learning Progress', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.students', 'Students', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.excursions', 'Excursions', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.gallery', 'Media Gallery', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.messages', 'Messages', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.ai', 'Teacher AI', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.performance', 'My Performance', 'Teacher', {'teacher'}),
  CatalogEntry('teacher.profile', 'Profile', 'Teacher', {'teacher'}, sensitive: true),
  CatalogEntry('teacher.community', 'Community', 'Teacher', {'teacher'}),
  CatalogEntry('driver.dashboard', 'Dashboard', 'Driver', {'driver'}, essential: true),
  CatalogEntry('driver.morning', 'Morning Run', 'Driver', {'driver'}),
  CatalogEntry('driver.afternoon', 'Afternoon Run', 'Driver', {'driver'}),
  CatalogEntry('driver.riders', 'Riders', 'Driver', {'driver'}),
  CatalogEntry('driver.route', 'Route & Stops', 'Driver', {'driver'}),
  CatalogEntry('driver.vehicle-check', 'Vehicle Check', 'Driver', {'driver'}),
  CatalogEntry('driver.incidents', 'Incidents', 'Driver', {'driver'}),
  CatalogEntry('driver.messages', 'Messages & Alerts', 'Driver', {'driver'}),
  CatalogEntry('driver.history', 'Trip History & Profile', 'Driver', {'driver'}),
  CatalogEntry('driver.community', 'Community', 'Driver', {'driver'}),
  CatalogEntry('parent.dashboard', 'Home', 'Parent', {'parent'}, essential: true),
  CatalogEntry('parent.children', 'My Children', 'Parent', {'parent'}, sensitive: true),
  CatalogEntry('parent.progress', 'Learning Progress', 'Parent', {'parent'}),
  CatalogEntry('parent.weekly-learning', 'Weekly Learning', 'Parent', {'parent'}),
  CatalogEntry('parent.assignments', 'Assignments', 'Parent', {'parent'}),
  CatalogEntry('parent.attendance', 'Attendance', 'Parent', {'parent'}),
  CatalogEntry('parent.finance', 'Finance & Payments', 'Parent', {'parent'}, sensitive: true),
  CatalogEntry('parent.messages', 'Messages', 'Parent', {'parent'}),
  CatalogEntry('parent.discussions', 'School Discussions', 'Parent', {'parent'}),
  CatalogEntry('parent.community', 'Community', 'Parent', {'parent'}),
  CatalogEntry('parent.school-life', 'School Life', 'Parent', {'parent'}),
  CatalogEntry('parent.documents', 'Documents & Consent', 'Parent', {'parent'}, sensitive: true),
  CatalogEntry('parent.ai', 'Parent AI', 'Parent', {'parent'}),
  CatalogEntry('parent.transferverify', 'TransferVerify Case', 'Parent', {'parent'}, sensitive: true),
  CatalogEntry('schoollife.community', 'Community', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.noticeboard', 'Noticeboard', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.activities', 'Activities & Clubs', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.events', 'Events', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.houses', 'Houses', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.gallery', 'Gallery', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.excursions', 'Excursions', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.transport', 'Transport', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.meals', 'Meals', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.boarding', 'Boarding', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.assembly', 'Assembly', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.visitors', 'Visitors', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.lost-found', 'Lost & Found', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.service', 'Service Projects', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.awards', 'Awards', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('schoollife.teaching-models', 'Teaching Models', 'School life', {'accountant', 'administrator', 'driver', 'parent', 'principal', 'proprietor', 'staff', 'student', 'teacher'}),
  CatalogEntry('general.dashboard', 'Dashboard', 'General', {'staff', 'student'}, essential: true),
  CatalogEntry('general.students', 'Students', 'General', {'staff'}),
  CatalogEntry('general.attendance', 'Attendance', 'General', {}),
  CatalogEntry('general.academics', 'Academics', 'General', {'student'}),
  CatalogEntry('general.messages', 'Messages', 'General', {'staff', 'student'}),
];